name: Zizmor Security Audit

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  zizmor:
    name: Audit GitHub Actions
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Needed to upload SARIF results to GitHub Security
      contents: read # Needed to checkout repository
      actions: read # Needed to analyze workflow files
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: zizmorcore/zizmor-action@70fb788f84895a7701f5643d103d587e460b5c99
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
